name: "Mutation tests"

on:
  pull_request:
  push:

jobs:
  mutation-tests:
    name: "Mutation tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.1 ]
        composer: [ highest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom
          coverage: xdebug
          tools: composer:v2

      - uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.composer }}"

      - name: "Infection"
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          vendor/bin/infection --git-diff-filter=A --logger-github
