name: "Unit Tests"

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    runs-on: ubuntu-latest
    strategy:
      php: ['8.0', 8.1, 8.2]
      stability: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom
          coverage: xdebug
          tools: composer:v2
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - uses: "ramsey/composer-install@v2"
        with:
          composer-options: "${{ matrix.stability }}"

      - name: composer validate
        run: composer validate --strict

      - name: Run unit tests
        run: "./vendor/bin/phpunit --colors=always --coverage-clover build/logs/clover.xml --coverage-text"

      - name: Publish coverage report to Codecov
        uses: "codecov/codecov-action@v2"
